### ISSUE TITLE
repeated types in the same message lead to duplicate *_elt names in .pyx file

### ISSUE THREAD

**Issue by jkm137** [appnexus/pyrobuf#10]
Given this message

message FooMessage {
repeated uint32 foo = 1;
repeated uint32 bar = 2;
}

I receive this error when compiling:

[1/1] Cythonizing 
test_proto.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        cdef int field_idx
        cdef int wire_type
        cdef int foo_marker
        cdef uint32_t uint32_elt
        cdef int bar_marker
        cdef uint32_t uint32_elt
                     
------------------------------------------------------------

test_proto.pyx:66:22: 'uint32_elt' redeclared

**Comment by 3kwa** [comment]
I believe I fIxed the issue in a long running PR https://github.com/appnexus/pyrobuf/pull/7

If you only want to patch master look at https://github.com/3kwa/pyrobuf/commit/b4a5ac693514db23dc9aa45ed55ff8281e2e6393

**Comment by jkm137** [comment]
Thanks!  That fixed the issue, though now, when I deserialize a bunch of data, I eventually see a bunch of these errors like this:

Exception SystemError: 'Negative size passed to PyString_FromStringAndSize' in 'FooProtos_proto.FooType._protobuf_deserialize' ignored

Then eventually it will seg fault.  This same data deserializes fine in Java and C#.  I'm still trying to narrow down the issue.  Have you seen this before?

**Comment by mmoresco** [comment]
Hm, I haven't seen that before. Could you provide the data that causes this to segfault?

**Comment by 3kwa** [comment]
I have encountered segfaults which were caused when using a version of pyrobuf_list generated and/or built for another platform.

If you are using pip try to force re install. The latest released version is 0.5.1.

If you are working from the repo run `python setup.py generate_list list_and_util`

Hopefully that helps.

**Comment by jkm137** [comment]
I uninstalled/reinstalled pyrobuf (v 0.5.1).  I can repro this on both windows and linux.  I'm running python 2.7.10.  I apologize that I've had to obfuscate the naming of everything in this example.  Also, this is a part of a bigger struct; I've stripped it down to the bare minimum required to reproduce the issue (that's why there are missing tags).

I receive the error below, then the seg fault:
Exception SystemError: 'Negative size passed to PyString_FromStringAndSize' in 'FooProtos_proto.Thing._protobuf_deserialize' ignored

proto definition:
message ThingPlayer {
optional uint64 BlahId = 1;
optional bool Active = 2;
repeated float Stats = 3;
}
 
message ThingTeam {
optional int32 BlahIndex = 1;
repeated float Stats = 2;
}
 
message ThingNotification {
optional uint32 BlahHash = 1;
optional uint64 BlahId = 2;
optional int32 BlahIndex = 3;
}
 
message ThingState {
repeated ThingPlayer Players = 1;
repeated ThingTeam Teams = 2;
repeated float GlobalStats = 3;
repeated ThingNotification Notifications = 4;
}
 
message Thing {
optional ThingState ThingState1 = 1;
}

message FooSubmessage {
optional Thing Thing1 = 5;
}

message FooBase {
optional FooSubmessage Sub = 3;
}

Python code to repro:
import FooProtos_proto
data = '\n\x07\x08\xd0\xcf\xd5\x90\x85*\x1a\x91\x08\x08\xd7\x01\x10\x8d\x15\x18\x00"\x00*\xc6\x07\n\xc2\x01\nj\x08\xb7\xb4\xba\xa2\x80\x80\x80\x80 \x10\x00\x1a\\\x00\x00\xa0A\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80?ff&?\xcd\xccL=\x00\x00\x80?\xcd\xccL=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x88A\x9a\x99Y?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00PA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80@\x00\x00\x00\x00\x12\x02\x08\x00\x1aP\x00\x00\xa0A\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80?ff&?\xcd\xccL=\x00\x00\x80?\xcd\xccL=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x88A\x9a\x99Y?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00PA\x00\x00\x00\x00\x00\x00\x80@\x00\x00\x00\x00\x12\xfe\x05\x08\xc5\xbb\xf2\x88\x08\x10\xc5\xbb\xf2\x88\x08\x18\xc5\xbb\xf2\x88\x08*\x0e\x08\xfc\x91\x9c\x99\x02\x10\x00\x18\x00 \x05(\x00*\x0e\x08\xcf\xbf\xc2\xd6\r\x10\x00\x18\x02 \x05(\x00*\x0e\x08\x9c\x9b\x93\x8c\x0b\x10\x00\x18\x02 \x05(\x00*\x0e\x08\xad\xa9\xd5\xfd\n\x10\x00\x18\x01 \x05(\x00*\x0e\x08\xe2\x82\xbe\xfb\x08\x10\x04\x18\x01 \x05(\x00*\x12\x08\x92\x8a\xf5\xa6\x0c\x10\x04\x18\xff\xff\xff\xff\x0f \x05(\x00*\x0e\x08\x84\xad\xb0\x98\x0e\x10\x00\x18\x01 \x05(\x00*\x12\x08\xb9\xb8\xeb\xe6\x04\x10\x04\x18\xff\xff\xff\xff\x0f \x05(\x00*\x0e\x08\x93\xdf\x93\x82\r\x10\x00\x18\x01 \x05(\x00*\x12\x08\xd4\xe3\x97\xa7\x05\x10\x04\x18\xff\xff\xff\xff\x0f \x05(\x00*\x0e\x08\xb3\x93\x9d\x86\r\x10\x00\x18\x01 \x05(\x00*\x12\x08\xb4\xe2\x87\xd7\x03\x10\x04\x18\xff\xff\xff\xff\x0f \x05(\x00*\r\x08\xb0\x80\x92n\x10\x00\x18\x01 \x05(\x00*\x12\x08\x85\x98\xbb\xd1\r\x10\x04\x18\xff\xff\xff\xff\x0f \x05(\x00*\x0e\x08\xa4\xf8\xd9\x89\x0f\x10\x00\x18\x01 \x05(\x00*\x12\x08\x99\x84\xa3\x8e\x0e\x10\x04\x18\xff\xff\xff\xff\x0f \x05(\x00*\r\x08\x9d\x8f\x98u\x10\x00\x18\x00 \x05(\x00*\x12\x08\xd4\xd5\xd8\xb6\x06\x10\x00\x18\xff\xff\xff\xff\x0f \x05(\x00*\x12\x08\x96\xcf\x92\xd8\n\x10\x00\x18\xff\xff\xff\xff\x0f \x05(\x00*\x0e\x08\xd0\xf1\x9f\xfe\x0c\x10\x00\x18\x00 \x05(\x002\x0e\x08\xfc\x91\x9c\x99\x02\x10\x00\x18\x00 \x05(\x002\x0e\x08\xcf\xbf\xc2\xd6\r\x10\x00\x18\x02 \x05(\x002\x0e\x08\x9c\x9b\x93\x8c\x0b\x10\x00\x18\x02 \x05(\x002\x0e\x08\xad\xa9\xd5\xfd\n\x10\x00\x18\x01 \x05(\x002\x0e\x08\xe2\x82\xbe\xfb\x08\x10\x04\x18\x01 \x05(\x002\x12\x08\x92\x8a\xf5\xa6\x0c\x10\x04\x18\xff\xff\xff\xff\x0f \x05(\x002\x0e\x08\x84\xad\xb0\x98\x0e\x10\x00\x18\x01 \x05(\x002\x12\x08\xb9\xb8\xeb\xe6\x04\x10\x04\x18\xff\xff\xff\xff\x0f \x05(\x002\x0e\x08\x93\xdf\x93\x82\r\x10\x00\x18\x01 \x05(\x002\x12\x08\xd4\xe3\x97\xa7\x05\x10\x04\x18\xff\xff\xff\xff\x0f \x05(\x002\x0e\x08\xb3\x93\x9d\x86\r\x10\x00\x18\x01 \x05(\x002\x12\x08\xb4\xe2\x87\xd7\x03\x10\x04\x18\xff\xff\xff\xff\x0f \x05(\x002\r\x08\xb0\x80\x92n\x10\x00\x18\x01 \x05(\x002\x12\x08\x85\x98\xbb\xd1\r\x10\x04\x18\xff\xff\xff\xff\x0f \x05(\x002\x0e\x08\xa4\xf8\xd9\x89\x0f\x10\x00\x18\x01 \x05(\x002\x12\x08\x99\x84\xa3\x8e\x0e\x10\x04\x18\xff\xff\xff\xff\x0f \x05(\x002\x0e\x08\xe1\xf1\xbe\x84\x02\x10\x00\x18\x02 \x01(\x002\x0e\x08\xb1\xa2\x8f\xc5\t\x10\x00\x18\x02 \x01(\x002\r\x08\x9d\x8f\x98u\x10\x00\x18\x00 \x05(\x002\x0e\x08\xff\x8c\xab\xd2\x05\x10\x00\x18\x02 \x01(\x002\x12\x08\xd4\xd5\xd8\xb6\x06\x10\x00\x18\xff\xff\xff\xff\x0f \x05(\x002\x12\x08\x96\xcf\x92\xd8\n\x10\x00\x18\xff\xff\xff\xff\x0f \x05(\x002\x0e\x08\xd0\xf1\x9f\xfe\x0c\x10\x00\x18\x00 \x05(\x000\x008\x00B\x04\x08\x04\x10\x00J\x00R\x00`\xd7\x01j\x16\x08\xe0\x95\x10\x10\x90\'\x18\xc0\x90\x01 \xc0\x07(\x90\x94*0\xe0\xe9[p\xae\xaf\xe0\xdf\x0ex\xb5\xcf\x84\xe6\xc1\xf3\x1d\x80\x01\xf4\xb3\xa6\xa4\x06'
foo = FooProtos_proto.FooBase()
foo.ParseFromString(data)

Does that repro for you?

**Comment by mmoresco** [comment]
It does, looking into it.

**Comment by 3kwa** [comment]
Using protoc decoding the message fails as well:
```
>>> FooBase.FromString(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eugene/miniconda/envs/pyrobuf/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 583, in FromString
    message.MergeFromString(s)
  File "/Users/eugene/miniconda/envs/pyrobuf/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 841, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/Users/eugene/miniconda/envs/pyrobuf/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 866, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "/Users/eugene/miniconda/envs/pyrobuf/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 827, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/Users/eugene/miniconda/envs/pyrobuf/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 797, in _RaiseInvalidWireType
    raise _DecodeError('Tag had invalid wire type.')
google.protobuf.message.DecodeError: Tag had invalid wire type.
```

**Comment by jkm137** [comment]
Odd.  I just regenerated the message using protoc 2.5.0 and it deserialized fine, producing this (which matches what the other languages yield when deserializing this):

Sub {
  Thing1 {
    ThingState1 {
      Players {
        BlahId: 2305843009285954103
        Active: false
        Stats: 20.0
        Stats: 0.0
        Stats: 0.0
        Stats: 1.0
        Stats: 0.649999976158
        Stats: 0.0500000007451
        Stats: 1.0
        Stats: 0.0500000007451
        Stats: 0.0
        Stats: 0.0
        Stats: 17.0
        Stats: 0.850000023842
        Stats: 0.0
        Stats: 0.0
        Stats: 0.0
        Stats: 0.0
        Stats: 0.0
        Stats: 0.0
        Stats: 13.0
        Stats: 0.0
        Stats: 0.0
        Stats: 4.0
        Stats: 0.0
      }
      Teams {
        BlahIndex: 0
      }
      GlobalStats: 20.0
      GlobalStats: 0.0
      GlobalStats: 0.0
      GlobalStats: 1.0
      GlobalStats: 0.649999976158
      GlobalStats: 0.0500000007451
      GlobalStats: 1.0
      GlobalStats: 0.0500000007451
      GlobalStats: 0.0
      GlobalStats: 0.0
      GlobalStats: 17.0
      GlobalStats: 0.850000023842
      GlobalStats: 0.0
      GlobalStats: 0.0
      GlobalStats: 0.0
      GlobalStats: 0.0
      GlobalStats: 13.0
      GlobalStats: 0.0
      GlobalStats: 4.0
      GlobalStats: 0.0
    }
  }
}

**Comment by jkm137** [comment]
Ah, I also get "Tag had invalid wire type" when I copy the data from the post above.  The page is removing certain characters, thus changing the data.  The attached file should be correct (had to name it .txt because the github uploader doesn't accept .py).

[pyrobufSegFaultExample.txt](https://github.com/appnexus/pyrobuf/files/108529/pyrobufSegFaultExample.txt)

**Comment by jkm137** [comment]
Any update on this?  Would it help if I could narrow this down to a simpler example?  Thanks for your help!

**Comment by mmoresco** [comment]
I believe it's related to an issue with varint decoding (we call FromStringAndSize with a bad size from from get_varint64 when calculating the size of ThingState1). Looking into it!

**Comment by mmoresco** [comment]
Hey @jkm137, how are you creating this serialized string? In the attached test file, when I recreate a test object with the exact same values, it serializes (using google protobuf) to a much smaller string.
[message_compare.txt](https://github.com/appnexus/pyrobuf/files/117601/message_compare.txt)

**Comment by jkm137** [comment]
That hex string comes from a larger protobuf struct that was filled out.  I chopped down the .proto definition to only those fields that were required to cause the segfault.  I can give the larger definition if that's useful, but the other data seems unrelated to the issue.

**Comment by mmoresco** [comment]
The larger definition + serialization would be helpful, thanks!

**Comment by jkm137** [comment]
[FooProtos.txt](https://github.com/appnexus/pyrobuf/files/118323/FooProtos.txt)

Here's the full definition. Again, sorry for the name obfuscation.  Thanks!

**Comment by mmoresco** [comment]
Hey @jkm137 I'm a little confused how this object was created - it looks like you have some int32s with values greater than the max allowed value for int32s (for example, the 6th Foo5 deserializes to 
``` Foo5 {
   Foo1: 3302835474
   Foo2: 4
   Foo3: 4294967295
   Foo4: 5
   Foo5: 0
 }```, the definition is ``` message ThingC {
optional uint32 Foo1 = 1;
optional int32 Foo2 = 2;
optional int32 Foo3 = 3;
optional int32 Foo4 = 4;
optional int32 Foo5 = 5;
} ```, and the max value for int32 is 2147483647.

**Comment by jkm137** [comment]
Odd, I see the same thing as you when I deserialize in python. The image below is what I get when I deserialize it in C# (it is -1 not 4294967295, which suggests it is treating that int as a uint for some reason).  The only other data that doesn't match my C# output is also a negative number (FooSubmessage.Blah10 is -336062546 instead of 3958904750, again just misinterpreting int as uint).

![image](https://cloud.githubusercontent.com/assets/8509465/12857041/d58a1314-cbfc-11e5-933f-c1620b59c232.png)

**Comment by mmoresco** [comment]
I _think_ there is an error in the C# encoding of int32s. When I serialize an int32 with value -1 in protobuf, the resulting bytes are [8, 255, 255, 255, 255, 255, 255, 255, 255, 1]. It looks like the bytes in your serialization are corresponding to that value are [08, 255, 255, 255, 255, 15]. The first one seems to be correct according to protobuf doc: `  If you use int32 or int64 as the type for a negative number, the resulting varint is always ten bytes long – it is, effectively, treated like a very large unsigned integer. `https://developers.google.com/protocol-buffers/docs/encoding?hl=en

**Comment by mmoresco** [comment]
Also, I've found 2 issues with pyrobuf so far in looking into this:

- We don't correctly serialize a field whose value is explicitly set to the default value - we handle this by not sending a value, but protobuf 2 will always send a value that is explicitly set (I believe in case the sending/receiving default values differ).

- We don't correctly ignore fields with ids we don't know about (so I was running into issues even after changing the defaults in your example test schema)

I think there might be further issues, because even after using your full schema on the debug serialization, pyrobuf still does not serialize correctly. I was trying to debug this further by recreating your example object, but ran into the int32 issue. If you send me another test serialization without the problem values, I'll continue looking into it!

Also, I will add better error handling for corrupt messages so we don't segfault on them :)

**Comment by jkm137** [comment]
Awesome :)

I attached a file with three more entries (one good, one more segfault, one truncated message error).  All three deserialize fine in the base python protobuf library (data looks fine except for the uint/int issue noted above).

As an FYI we use protobuf-net in C#, the default protobuf library in Java, and Nanopb in c++.  This data is actually generated in C++, and the values all match between those three implementations.  Python is the only oddity, so I'm tempted to say that the default library is wrong.  That said, the link you added to the protobuf docs above is pretty clear; that makes it sound like all three of the other libraries is wrong :/

[moreDataExamples.txt](https://github.com/appnexus/pyrobuf/files/120026/moreDataExamples.txt)

**Comment by mmoresco** [comment]
Hm, for the two broken examples you provided, pyrobuf ParseFromString does indeed break, but deserializing/reserializing the data using google protobuf provides a serialization that correctly deserializes in pyrobuf. For example:

```
bad_foo = FooBase.FromString(bad_data)
my_foo.ParseFromString(bad_foo.SerializeToString())
my_foo.ParseFromString(bad_data)
```

the first parse works, but the second one fails. It looks like the serialization generated by google protobuf is very different (for all three examples) from the original serialization provided (different lengths, and the byte values look very different). Do you know of anything that might be causing this discrepancy? Maybe an issue with nanopb?

**Comment by jkm137** [comment]
I'm trying to track down the difference in encoding.  I'll try to get a good nanopb example to compare.  In doing that, I stumbled across this issue.  In the attached example, the native protobuf serializes to the same things as C#, but the pyrobuf SerializeToString() call causes python to consume more and more memory (many GBs) and never completes. 

[memoryUsageExplosion.txt](https://github.com/appnexus/pyrobuf/files/125279/memoryUsageExplosion.txt)

**Comment by mmoresco** [comment]
Thanks for catching that, I'll take a look.

Question though, I had to change your example test to 
   ``` 
foo = ffff_proto.FooBase()
event_id = ffff_proto.EventId()
event_id.EventTime = 1
foo.Id = event_id
 ``` 
to avoid `Exception: required field 'Id' not initialized and does not have default` - does this file run for you as is?

**Comment by mmoresco** [comment]
Negative varint fix is merged, version 0.5.3 is available in pypi with the fix. Thanks for catching that!

**Comment by jkm137** [comment]
Yeah, I had to make the same change, but hadn't saved the example file.  Sorry!   

I updated to 0.5.3 and rebuilt FooProtos_proto, but I'm still hitting the same issue.  To help rule things out, when I compile the .proto, I see a bunch of warnings like this (I was seeing them before as well):
FooProtos_proto.c(2731) : warning C4244: '=' : conversion from 'int64_t' to 'int', possible loss of data

Do you see those as well?

**Comment by mmoresco** [comment]
Hm, I don't see that. Did you do `pip install pyrobuf -v -v -v --upgrade --force`? If that still doesn't work, can you try running the tests on your end and see if they pass?

**Comment by jkm137** [comment]
I tried that and I hit the same issue (in Windows).  Then I went to test it on linux (Ubuntu), and it worked fine.  I think that warning is key.  I verified that the output cython file FooProtos_proto.c are identical on both platforms.

I still hit the segfault on both platforms.  Can you think of anything else I can provide to help with that?

Thanks!

**Comment by mmoresco** [comment]
Are you able to run the tests successfully on Windows?

I'm not sure how to address the segfault without knowing more about the encoding discrepancy mentioned above - if the serialization provided doesn't conform to the protobuf spec, we unfortunately can't know how to correctly deserialize it.
