### ISSUE TITLE
Possible to export pyrobuf_modules as submodules?

### ISSUE THREAD

**Issue by carsonfarmer** [appnexus/pyrobuf#108]
It would be nice to be able to do something like `from package.proto import Message`, rather than two separate top-level packages:

```
from package import other_stuff
from message_proto import Message
```

This should be possible with cython and Extensions I think...

**Comment by tburmeister** [comment]
Hi Carson,

I'm going to mark this as a duplicate since I think you are asking for essentially the same thing as in #107, or at least the solution for that should provide a solution here as well. I agree this would be a nice feature.

**Comment by carsonfarmer** [comment]
Yes you are right, this is a duplicate of that issue. Apologies!
