### ISSUE TITLE
Support for message methods such as CopyFrom, MergeFrom and SerializePartialToString

### ISSUE THREAD

**Issue by grgsrs** [appnexus/pyrobuf#16]
Currently pyrobuf does not support some of the various protobuf message methods such as `CopyFrom`, `MergeFrom` and `SerializePartialToString`. Rather the create a rather large pull-request without warning, I thought I'd create this issue so that the changes could be discussed beforehand.

The changes can be seen in [my fork](https://github.com/grgsrs/pyrobuf).

I've done my best to keep the performance as fast as possible. However, the deserialization performance has noticeably dropped. On my machine serialization takes on average 0.634480 seconds with pyrobuf 0.5.4 and 0.592283 seconds after my changes. Deserialization takes on average 0.416573 seconds with pyrobuf 0.5.4 and 0.632511 seconds after my changes.

One reason for the drop in performance is that I've modified the message validation code to check sub-messages as-well. Pyrobuf's `ParseFromString` method does validate a message after deserialization, while Google's protobuf does not, so performance could be improved by dropping message validation in `ParseFromString` (my guesstimate is that this would cut deserialization time by approximately 0.06 seconds).

**Comment by mmoresco** [comment]
Hm, a 1.5x drop is not great, but we definitely want to work towards full parity with google protobuf. What do you think about maybe having two versions of messages available to generate (a speedier one and a fully functional one) so folks could make their own choice about performance vs having use of those methods?

Also, do you know why serialization speed improved with your changes?

**Comment by grgsrs** [comment]
For deserialization, pyrobuf is currently spending a substantial amount of time resetting the message object, so if you knew ahead of time that you didn't need to reset the object, you could dramatically cut the deserialization time by using `MergeFromString` rather than `ParseFromString`. Also, as I mentioned before, pyrobuf's `ParseFromString` performs message validation which Google's `ParseFromString` does not, so that could save some time.

After digging deeper into the Cython documentation, I've found a [faster way to instantiate](http://docs.cython.org/src/userguide/extension_types.html#fast-instantiation) message objects and scalar lists, which cuts the amount of time required to reset a message object. I currently have it averaging 0.533546 seconds for Deserialization, and this drops to 0.487844 seconds if you turn off message validation in `ParseFromString`. Avoiding the reset step by calling `MergeFromString` or `ParseFromString(reset=False)` drops the deserialization time to around 0.24 seconds.

For serialization, I made use of Cython's `for i in range` [optimization](http://docs.cython.org/src/reference/language_basics.html#for-loops) to make the loops more efficient and used type-casting to take advantage of Cython's faster operations on known types. Non-packed repeated fields were using a while loop which would never iterate more than once, so I cut the loop out. The lengths of repeated field lists were being computed twice, so I recorded the first result to avoid calculating it again. Finally, sub-messages were being serialized even if they weren't initialized (resulting in a zero-length bytearray), so I inserted a test to avoid serialization in that case.

**Comment by grgsrs** [comment]
Another option to speed things up would be to cheat...

Currently you'll get the same results for the following code whether you use protobuf or pyrobuf:

```python
>>> t = test_message_pb2.Test()   # for pyrobuf use t = test_message_proto.Test()
>>> s = t.substruct
>>> t.Clear()   # use t.reset() in pyrobuf 0.5.4
>>> t.substruct is s
False
```

This is because an entirely new substruct object is created when the message is cleared/reset. You could cheat by simply clearing the original substruct object rather than creating a new one. Since clearing an existing object is faster than creating a new one, this will speed up message clearing.

The down side is that code like the following will have different results in pyrobuf vs protobuf:

```python
>>> t = test_message_proto.Test()
>>> s = t.substruct
>>> s.field1 = 54321
>>> t.Clear()
>>> s.field1 == 54321
True   # This will be False if you only clear the substruct rather than creating a new one
```

To implement this cheat, you could add an optional keyword argument to the `Clear`, `ClearField`, `CopyFrom` and `ParseFrom*` methods like this:

```python
def ParseFromString(self, data, size=None, reset=True, pyrobuf_do_recycle=False):
    ...
    if reset:
        if pyrobuf_do_recycle:
            self.recycle()
        else:
            self.reset()
    ...
```

**Comment by grgsrs** [comment]
By in-lining a method call I got the deserialization time down to around 0.51 seconds with message validation in `ParseFromString` around 0.41 seconds without message validation.

**Comment by grgsrs** [comment]
Further cythonization, including restoring a type definition I accidentally removed, has dropped deserialization time to 0.428 seconds on average with message validation and 0.399 without message validation.

**Comment by 3kwa** [comment]
@mmoresco @grgsrs that is looking good!
I turned to pyrobuf because I was looking for speed  but would not have been able to use it without the API call I needed (I added a simplified version of FromString which @grgsrs tells me he can speed up \o/).
No speed loss now and API gain is +1 from me ;)

**Comment by grgsrs** [comment]
Thanks @3kwa 

Here's some benchmark comparisons I've done using my fork (called "NOW" in the benchmark results) versus pyrobuf 0.5.4 (called 0004 in the results) with message validation turned on in `ParseFromString`:

```
---------------------------------------------------------------------------- benchmark 'deserialize': 2 tests ---------------------------------------------------------------------------
Name (time in us)                              Min                 Max              Mean            StdDev            Median               IQR            Outliers(*)  Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_parse_from_string_benchmark (0004)     3.3204 (1.0)       56.5974 (1.0)      3.8181 (1.0)      0.8804 (1.0)      3.7732 (1.0)      0.1509 (1.0)        3361;5472  150586           2
test_parse_from_string_benchmark (NOW)      3.4713 (1.05)     373.5431 (6.60)     4.0013 (1.05)     1.3222 (1.50)     3.9241 (1.04)     0.1509 (1.0)        3835;6321  144038           2
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------- benchmark 'fromstring': 2 tests -------------------------------------------------------------------------
Name (time in us)                        Min                 Max              Mean            StdDev            Median               IQR            Outliers(*)  Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_from_string_benchmark (NOW)      3.6222 (1.0)      385.0135 (4.20)     4.1505 (1.0)      1.7518 (1.58)     4.0750 (1.0)      0.1509 (1.0)        3771;6462  138037           2
test_from_string_benchmark (0004)     4.3769 (1.21)      91.6124 (1.0)      5.0499 (1.22)     1.1098 (1.0)      4.9806 (1.22)     0.1509 (1.00)       3086;8132  110430           2
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------ benchmark 'serialize': 2 tests -----------------------------------------------------------------------------
Name (time in us)                                Min                 Max              Mean            StdDev            Median               IQR            Outliers(*)  Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_serialize_to_string_benchmark (NOW)      6.3389 (1.0)      591.6319 (1.0)      7.3820 (1.0)      2.2897 (1.0)      7.2445 (1.0)      0.3019 (1.0)        3830;5582  150586           1
test_serialize_to_string_benchmark (0004)     7.5463 (1.19)     741.3509 (1.25)     8.5421 (1.16)     2.8466 (1.24)     8.1500 (1.13)     0.3019 (1.00)       3029;8859  132515           1
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

(*) Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
```

Using the mean times, `ParseFromString` is about 5% slower, `FromString` is significantly faster (it's now using `MergeFromString` instead of `ParseFromString`) and `SerializeToString` is moderately faster aswell.

If I turn off message validation in `ParseFromString` I get:

```
--------------------------------------------------------------------------- benchmark 'deserialize': 2 tests ---------------------------------------------------------------------------
Name (time in us)                              Min                Max              Mean            StdDev            Median               IQR            Outliers(*)  Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_parse_from_string_benchmark (NOW)      3.1695 (1.0)      34.2603 (1.0)      3.7859 (1.0)      0.8630 (1.0)      3.6222 (1.0)      0.1509 (1.0)        3730;6736  150586           2
test_parse_from_string_benchmark (0004)     3.3204 (1.05)     56.5974 (1.65)     3.8181 (1.01)     0.8804 (1.02)     3.7732 (1.04)     0.1509 (1.0)        3361;5472  150586           2
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

I'm using the [pytest-benchmark](https://github.com/ionelmc/pytest-benchmark) package to do the benchmark testing.

**Comment by 3kwa** [comment]
A significantly faster FromString :v:

**Comment by mmoresco** [comment]
Nice, this is awesome!! Could you put together a pull request?
