### ISSUE TITLE
Support for [deprecated=true] options

### ISSUE THREAD

**Issue by ser0t0nin** [appnexus/pyrobuf#19]
When a .proto-file has a property with [deprecated=true] option, building failes with something like this:

```
  File "/usr/local/lib/python2.7/dist-packages/pyrobuf_list_and_util-0.5.4-py2.7-linux-x86_64.egg/pyrobuf/parse_proto.py", line 137, in tokenize
    raise Exception("Unexpected character '%s' in line %d: '%s'" % (s[pos], line, s[pos-10:pos+10]))
Exception: Unexpected character 'r' in line 41: ' = 2;
    required u'
```
After deleting this option, everything goes well. Thus, it affects true protobuf compability

**Comment by tburmeister** [comment]
Working on a fix for this now - should have a PR up soon.

**Comment by 3kwa** [comment]
Thanks @tburmeister
