### ISSUE TITLE
Trying to run the code and it crashes on missing "test_message_proto"

### ISSUE THREAD

**Issue by katiahuri** [appnexus/pyrobuf#29]
When running this line : from test_message_proto import Test
The code crashes and returns:
ImportError: No module named test_message_proto
Tried to look for this file and it does not exist, what am I doing wrong?

**Comment by grgsrs** [comment]
Could you give us a little more information? Which version of Python are you using, on what platform? How are you running the tests?

**Comment by katiahuri** [comment]
2.7.11 on Windows unfortunately, and I installed the library with pip
install (by the way, I was missing the stdint.h file, so I downloaded it
and installed it with running setup.py
After that I've trired to run the tests, so I guess Im missing a step or
 something
Thanks for your response!

**Comment by grgsrs** [comment]
Hi Katia,

The error message you've described means that the first stage of testing, which is building the test proto modules, has not worked. Could you supply us with the full output on the console when you run the tests, including the command used to run them?

**Comment by katiahuri** [comment]
I have no errors while compiling the library after cloning the source code
and no problems in pip installing it.
But when Im trying to use it, it fails with "no reference" on this line:
from test_message_proto import Test

**Comment by neRok00** [comment]
I was having this problem in my virtualenv too, as even though everything appeared to be working when doing `pyrobuf mytest.proto` (ie. no errors), I could not then do `from mytest_proto import  *` as I was getting the '_ImportError: No module named_' error.

The solution was to instruct pyrobuf to install the resulting files as a package via `pyrobuf --install mytest.proto`.

IMO, this requirement was not spelled out enough on the 'homepage'. Perhaps a little more info in/around the **Compiling** and **Use** sections would make it clearer?
