### ISSUE TITLE
SerializeToString errors with 'can't concat str to bytearray' in Python 3.5

### ISSUE THREAD

**Issue by sstirlin** [appnexus/pyrobuf#31]
I'm trying to run the test example in the README on Python 3.5.  I get the error:

 t.SerializeToString()
Exception ignored in: 'test_message_proto.Test._protobuf_serialize'
TypeError: can't concat str to bytearray
Out[19]: bytearray(b'\x10\x05\x1a\x04')

**Comment by grgsrs** [comment]
Hi sstirlin,

There are a number of known problems with pyrobuf 0.5.7 and python 3.5. If you could hold off till the next release, hopefully things will be fixed.

**Comment by 3kwa** [comment]
@sstirlin would you care to check if your problem has been addressed by recent releases?

**Comment by tburmeister** [comment]
Appears to now be working.
