### ISSUE TITLE
Update PyPI with latest version

### ISSUE THREAD

**Issue by claws** [appnexus/pyrobuf#37]
Any chance you can you push the current version to PyPI?

Using Python 3.5 on OSX (10.11.14) I tried to ``pip install pyrobuf`` and received the following error:

```
$ pip install pyrobuf
Collecting pyrobuf
  Downloading pyrobuf-0.5.7.tar.gz (157kB)
...
...
pyrobuf/src/pyrobuf_list.c:27383:2: error: __getslice__, __setslice__, and __delslice__ not supported in Python 3.
    #error __getslice__, __setslice__, and __delslice__ not supported in Python 3.
```

When I clone the repo (0.5.8) and install using `` python setup.py install`` it works fine.

**Comment by 3kwa** [comment]
Done!
