### ISSUE TITLE
Expose utilities to support streaming

### ISSUE THREAD

**Issue by claws** [appnexus/pyrobuf#41]
Google Protocol Buffers (GPB) is not self delimiting and hence the typical parser does not understand where one message ends and the next begins in a stream containing multiple types. A common technique is to use a length field prefixed to the start of each message. This is mentioned in the [streaming](https://developers.google.com/protocol-buffers/docs/techniques#streaming) section of the GPB docs. This technique allows many different types to be sent over a single stream - which describes my use case.

[Here](https://github.com/slok/prometheus-python/blob/master/prometheus/formats.py#L301) is an example of this use case in a Python package using the GPB implementation (by accesses an internal function). I'd like to use ``pyrobuf`` to do the same thing - but using a public API.

To support this use case, I am requesting that ``pyrobuf`` expose a utility function allowing the developer to encode (and decode) an integer into the varint format so they could prefix the encoded bytes onto encoded message bytes prior to sending.

**Comment by grgsrs** [comment]
Hi Claws,

Though regrettably not documented, the `pyrobuf_util` module contains the following functions which seem like they meed your needs:

- [get_varint](https://github.com/appnexus/pyrobuf/blob/master/pyrobuf/src/pyrobuf_util.pyx#L87)
- [get_signed_varint](https://github.com/appnexus/pyrobuf/blob/master/pyrobuf/src/pyrobuf_util.pyx#L132)
- [to_varint](https://github.com/appnexus/pyrobuf/blob/master/pyrobuf/src/pyrobuf_util.pyx#L177)
- [to_signed_varint](https://github.com/appnexus/pyrobuf/blob/master/pyrobuf/src/pyrobuf_util.pyx#L225)

Would those methods satisfy your request?

**Comment by claws** [comment]
@grgsrs Yes, that will do the trick. Thanks.

I think your project would benefit from having these useful methods documented. It definitely would have saved me from searching around for another library to do that job. It might be worth leaving this PR open (or raise a new one) to add some docs describing how the ``pyrobuf`` library supports this use case. This is actually better than the GPB library as the methods are public (just undocumented).

**Comment by claws** [comment]
Hmm, maybe not quite. When decoding the binary data after receiving it over a stream I am expecting to start by reading a varint from the length delimited blobs. The methods in the ``pyrobuf_util`` module let me do that but but don't tell me how many bytes the varint was encoded in. This means I don't know how many bytes to strip off the front of the data before getting to the actual message data.

Its almost like I need the ``get_varint`` to return the value and the number of bytes that the varint was encoded into so I can stip that many bytes off before starting to parse the message data.

Any ideas?

**Comment by grgsrs** [comment]
I'm hoping that PR [43](https://github.com/appnexus/pyrobuf/pull/43) fixes this issue.

**Comment by claws** [comment]
Looks good to me. Thanks.
