### ISSUE TITLE
Proto3

### ISSUE THREAD

**Issue by jacmarjorie** [appnexus/pyrobuf#42]
Any development paths to support proto3? I was excited to give pyrobuf a try, but have already migrated to proto3 after the fact.

**Comment by 3kwa** [comment]
I have never looked into the difference between the two versions as we are "stuck" in proto2 world. Would you be interested in having a crack at making pyrobuf support proto3?

**Comment by 3kwa** [comment]
@jacmarjorie are you attending Pycon?

**Comment by helenakristina** [comment]
I would also love to see support for proto3.

**Comment by tburmeister** [comment]
I think this mostly requires writing and linking in a new parser, though for some added efficiency we could skip all the `isSet` and field listener stuff since proto3 has no "required" fields.

**Comment by tburmeister** [comment]
Just put up a pull request for this: https://github.com/appnexus/pyrobuf/pull/60

Think this is actually pretty straightforward.

**Comment by goldenbull** [comment]
proto3 👍

**Comment by tburmeister** [comment]
@goldenbull have you checked out my branch from PR #60? Would love some feedback and testing.

**Comment by tburmeister** [comment]
Merged in changes that should allow for basic proto3 support, though as noted in PR, reserved keyword is not currently supported - created a new issue for it: #76
