### ISSUE TITLE
better support for distribution of pyrobuf processed content in packages

### ISSUE THREAD

**Issue by claws** [appnexus/pyrobuf#45]
I'm trying to work out how I can distribute a package that includes a proto module that needs to be built with ``pyrobuf``. In my distributed package I want to be able to access the generated module from within my package namespace using something like ``from mypackage.subpackage import generated_proto_module``. I can't work out how to do this using ``pyrobuf``.

This use case seem reasonable to me, but perhaps I'm missing something in ``pyrobuf`` that would let me achieve this. I can't find any examples showing how I could achieve this using the ``pyrobuf`` tooling. 

Reading the docs it appears that ``pyrobuf`` CLI will install each ``.proto`` file as a completely separate Python package, but I want any generated modules to be located within my package namespace.

I think I need to use ``pyrobuf`` to process my ``.proto`` into ``.pyx`` and ``.pxd`` files, which I would then add to the project source tree as version controlled files which would be distributed. The extension would get built when the package is being installed on a client machine. Assuming this approach makes sense...

The problem I'm having is trying to determine how to use ``pyrobuf`` to process the ``.proto`` file in such a way that I can include the ``.pyx`` and ``.pxd`` files in my distribution so they can be built into an extension when the package is installed on the client machine. At present the CLI ``__main__`` seems hard coded to always goes one step too far (at least for my use case) by always building the extension. I think what I need is the output of the ``gen_message`` function but excluding the ``cythonize`` and ``setup``. 

Perhaps the CLI ``__main__`` could be modified to build the extension based on an extra flag (e.g. ``--build``) similar to the ``install`` flag? That way it would work as before but also for my use case. I could say ``--build=False`` so I just end up with the ``.pyx`` and ``.pxd`` files.

**Comment by grgsrs** [comment]
In [pull request 46](https://github.com/appnexus/pyrobuf/pull/46) I've added some documentation for the `pyrobuf_modules` setup keyword which aids the distribution of pyrobuf modules with your own Python packages.

Unfortunately the pyrobuf modules are installed at the top level, not within your own package's namespace as you were hoping.

**Comment by claws** [comment]
@grgsrs thanks, those docs additions helped me get something working.

Perhaps, installing the extensions into a package namespace could be recorded somewhere as an enhancement request. This would be most useful for one of my other projects (which is why I'm evaluating pyrobuf in a simple project) which has thousands of system messages definitions.

I'll close out this PR as the info in #46 helped me develop a workable solution.
