### ISSUE TITLE
lacks a license

### ISSUE THREAD

**Issue by jap** [appnexus/pyrobuf#6]
Hi,

Could you add a license to this project? Without one I can't use it :(

Thanks!

**Comment by jhuttner** [comment]
Hello, please see the LICENSE file.  This project is licensed under the Apache License, Version 2.0.

https://github.com/appnexus/schema-tool/blob/master/LICENSE

**Comment by jap** [comment]
I'm talking about the pyrobuf repository, which does not seem to be part of schema-tool.

**Comment by jhuttner** [comment]
Yes, sorry, comment updated above.
