### ISSUE TITLE
Support of default value in optional field

### ISSUE THREAD

**Issue by slxiao** [appnexus/pyrobuf#94]
When there is default value for optional field, for example

optional uint32 badQualityULGapThres = 3[default =10];

pyrobuf command will throw exceptions. It seems pyrobuf not supports this function. Is is right?

**Comment by tburmeister** [comment]
Defaults are supported; you need a space between `3` and `[default=10]`.

**Comment by slxiao** [comment]
Thank you for your help. It works. I will close this issue
