### ISSUE TITLE
Support oneof function

### ISSUE THREAD

**Issue by slxiao** [appnexus/pyrobuf#95]
When proto file contains oneof field, pyrobuf wil throw exception. It seems pyrobuf not supports oneof. It that true?

**Comment by tburmeister** [comment]
That is correct, we do not currently support `oneof` fields.

**Comment by slxiao** [comment]
Thanks. Got it.

**Comment by OOthomasOO** [comment]
Hm, what approach do you recommend for working around this? 

I am porting some stuff that uses protobuff and makes heavy use of "oneof".

**Comment by AlmogCohen** [comment]
@tburmeister Any good reason to not implement that or is it just something you couldn't get to? If I try to implement that and propose a PR would it be acceptable? Did the team here tried to implement that and encountered some things that they couldn't get around? Thanks!

**Comment by tburmeister** [comment]
Hi Almog,

I never got around to implementing oneof since it's not a feature we use. A
PR would be great.

Best,
Taylor
